### ISSUE TITLE
For Linux users

### ISSUE THREAD

**Issue by abdellatif-temsamani** [bitbrain/godot-dash#1]
Pro tip for linux users 
* open terminal 
* git clone https://github.com/bitbrain/godot-dash
* cd godot-dash
* cp editor_settings-3.tres $HOME/.config/godot

if you should have one there but it’s no problem to overwrite it and don’t forget to install the fonts

**Comment by bitbrain** [comment]
Hey @abdellatif-dev  could you raise a PR against the README.md please to suggest your how-to? Thank you.
