### ISSUE TITLE
Godot 4 support

### ISSUE THREAD

**Issue by Atickxxx** [bitbrain/godot-dash#4]
So when i modify the editor_settings-4 file and launch godot the theme Is not showing and the file Is rewrite after.

- I'am  on windows 11 64bit
- Godot_v4.0-alpha13_win64
- Installed in my document folder

**Comment by bitbrain** [comment]
@Atickxxx the problem might be Godot 4 here. Let me have a look today, I might be able to port this theme to Godot 4 for you, as this theme only works officially on Godot 3

**Comment by Atickxxx** [comment]
great thank you very much

**Comment by bitbrain** [comment]
Addressed with https://github.com/bitbrain/godot-dash/pull/5
